
import './globals.css'
import { Rubik } from 'next/font/google'

// componets
import Navbar from './components/Navbar'


const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Ticket Listing',
  description: 'Generated by BotMind',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
       <Navbar />
        {children}
        </body>
    </html>
  )
}
